// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "ack_deadline_seconds" {
  type = number
}
variable "enable_message_ordering" {
  type = bool
}
variable "gcp_authentication" {
  type = object({
    auth_provider_x509_cert_url = string
    auth_uri                    = string
    client_email                = string
    client_id                   = string
    client_x509_cert_url        = string
    private_key                 = string
    private_key_id              = string
    project_id                  = string
    token_uri                   = string
    type                        = string
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "message_retention_duration_seconds" {
  type = number
}
variable "minimum_backoff_seconds" {
  type = number
}
variable "monitoring_configuration" {
  type = object({
    backlog_bytes_above = optional(number)
  })
}
variable "retain_acked_messages" {
  type = bool
}
variable "subnetwork" {
  type = object({
    infrastructure = object({
      cidr                   = string
      gcp_global_network_grn = string
      grn                    = string
      vpc_access_connector   = string
    })
    specs = object({
      gcp = optional(object({
        project = optional(string)
        region  = optional(string)
      }))
    })
  })
}
variable "topic" {
  type = object({
    infrastructure = object({
      grn = string
    })
    security = object({
      iam = optional(map(object({
        condition = string
        role      = any
      })))
    })
    specs = object({
      topic = optional(object({
        distribution = string
      }))
    })
  })
}
